var data = [
    {
        "name": "GEORGE H. W. BUSH (1989-1993)",
        "populationstart": 250,
        "populartionend": 261,
        "gdpstart": 8.786,
        "gdpend": 9.52,
        "inflation": 13,
        "deptstart": 4.48,
        "deptend": 5.69,
        "surplusstart": -239,
        "surplusend": -413,
        "aidcurrent": 49907241.9,
        "aidconstant": 80177477.29,
        "incarcerationstart": 712400,
        "incarcerationend": 969300,
        "deportationstart": 865317,
        "deportationend": 1149500,
        "crimesstart": 4589,
        "crimesend": 7603,
        "shootingsvictims": 115,
        "shootingsincidents": 7,
        "intervation": "In Operation Just Cause in 1989, 24,000 American troops were ordered into Panama to overthrow Panamanian leader, General Manuel Noriega. Bush Sr also authorised the use of military power following the 1990 Iraq invasion of Kuwait. During the Somali civil war, the Bush Sr administration sent forces to protect humanitarian aid supply lines in the famine-stricken nation. "
    },
    {
        "name": "BILL CLINTON (1993-1997)",
        "populationstart": 260,
        "populartionend": 273,
        "gdpstart": 9.52,
        "gdpend": 11.03,
        "inflation": 9,
        "deptstart": 6.05,
        "deptend": 6.9,
        "surplusstart": -354,
        "surplusend": -28.1,
        "aidcurrent": 20463248.27,
        "aidconstant": 29845071.11,
        "incarcerationstart": 969300,
        "incarcerationend": 1240700,
        "deportationstart": 1285952,
        "deportationend": 1555116,
        "crimesstart": 7603,
        "crimesend": 8778,
        "shootingsvictims": 98,
        "shootingsincidents": 7,
        "intervation": "Clashes between US forces and armed groups continued in Somalia. In 1995, US forces targeted Bosnian Serbs who had been attacking UN safe zones. American peacekeepers were deployed later in the year to Bosnia to uphold the Dayton Peace agreement. Clinton ordered missile strikes on al-Qaeda targets in Afghanistan and Sudan in 1998 during Operation Infinite Reach in reprisal for attacks on US embassies in Kenya and Tanzania. Clinton authorised the use of US forces in a NATO bombing raid on Yugoslavia after human rights violations were committed against Albanians in Kosovo. At the end of 1998, Clinton launched a four-day bombing campaign in Iraq. Between 1999 and 2000, the US – along with Britain – attacked Iraqi air defences more than 200 times."
    },
    {
        "name": "BILL CLINTON (1997-2001)",
        "populationstart": 273,
        "populartionend": 286,
        "gdpstart": 11.035,
        "gdpend": 12.682,
        "inflation": 7,
        "deptstart": 6.9,
        "deptend": 6.91,
        "surplusstart": -28.1,
        "surplusend": 290,
        "aidcurrent": 17553196.76,
        "aidconstant": 23922473.34,
        "incarcerationstart": 1240700,
        "incarcerationend": 1404000,
        "deportationstart": 1555116,
        "deportationend": 1864343,
        "crimesstart": 8049,
        "crimesend": 9730,
        "shootingsvictims": 160,
        "shootingsincidents": 11,
        "intervation": "Clashes between US forces and armed groups continued in Somalia. In 1995, US forces targeted Bosnian Serbs who had been attacking UN safe zones. American peacekeepers were deployed later in the year to Bosnia to uphold the Dayton Peace agreement. Clinton ordered missile strikes on al-Qaeda targets in Afghanistan and Sudan in 1998 during Operation Infinite Reach in reprisal for attacks on US embassies in Kenya and Tanzania. Clinton authorised the use of US forces in a NATO bombing raid on Yugoslavia after human rights violations were committed against Albanians in Kosovo. At the end of 1998, Clinton launched a four-day bombing campaign in Iraq. Between 1999 and 2000, the US – along with Britain – attacked Iraqi air defences more than 200 times."
    },
    {
        "name": "GEORGE BUSH JR (2001-2005)",
        "populationstart": 286,
        "populartionend": 296,
        "gdpstart": 12.68,
        "gdpend": 14.23,
        "inflation": 10,
        "deptstart": 6.92,
        "deptend": 8.66,
        "surplusstart": 154,
        "surplusend": 349,
        "aidcurrent": 5461915.343,
        "aidconstant": 6863128.143,
        "incarcerationstart": 1404000,
        "incarcerationend": 1525900,
        "deportationstart": 1538397,
        "deportationend": 1343351,
        "crimesstart": 9730,
        "crimesend": 7163,
        "shootingsvictims": 36,
        "shootingsincidents": 3,
        "dronepakistan": "2004 onwards: 424",
        "dronesomalia": "2002 onwards: 137-157",
        "intervation": "Bush launched the so-called “war on terror” after the 9-11 attacks on the World Trade Center. The US led the NATO invasion of Afghanistan. During his second term, in 2003, Bush declared war on Iraq, claiming the country was producing weapons of mass destruction."
    },
    {
        "name": "GEORGE BUSH JR (2005-2009)",
        "populationstart": 296,
        "populartionend": 307,
        "gdpstart": 14.20,
        "gdpend": 14.4,
        "inflation": 7,
        "deptstart": 8.66,
        "deptend": 10.1,
        "surplusstart": 349,
        "surplusend": -464,
        "aidcurrent": 6348233.899,
        "aidconstant": 7199533.946,
        "incarcerationstart": 1525900,
        "incarcerationend": 1615500,
        "deportationstart": 1343351,
        "deportationend": 1171058,
        "crimesstart": 7163,
        "crimesend": 7783,
        "shootingsvictims": 181,
        "shootingsincidents": 12,
        "dronepakistan": "2004 onwards: 424",
        "droneyemen": "2007 onwards: 32-36",
        "dronesomalia": "2002 onwards: 137-157",
        "intervation": "Bush launched the so-called “war on terror” after the 9-11 attacks on the World Trade Center. The US led the NATO invasion of Afghanistan. During his second term, in 2003, Bush declared war on Iraq, claiming the country was producing weapons of mass destruction."
    },
    {
        "name": "BARACK OBAMA (2009-2013)",
        "populationstart": 307,
        "populartionend": 315,
        "gdpstart": 14.4,
        "gdpend": 15.3,
        "inflation": 7,
        "deptstart": 11.9,
        "deptend": 15.3,
        "surplusstart": -1000.41,
        "surplusend": -1000.04,
        "aidcurrent": 6266121.081,
        "aidconstant": 6631630.068,
        "incarcerationstart": 1615500,
        "incarcerationend": 1570400,
        "deportationstart": 974047,
        "deportationend": 647641,
        "crimesstart": 7783,
        "crimesend": 6573,
        "shootingsvictims": 128,
        "shootingsincidents": 8,
        "dronepakistan": "2004 onwards: 424",
        "droneyemen": "2007 onwards: 32-36",
        "dronesomalia": "2002 onwards: 137-157",
        "intervation": "Under Obama, the US formally ended its combat mission in Iraq in August 2010.  In 2009, 30,000 more military personnel were deployed to Afghanistan in an attempt to bolster the US presence in the country. In a special operation, US Navy SEALS infiltrated a compound in Pakistan, killing Osama bin Laden. During his second term, Obama ordered air strikes on the Libyan government’s air defence facilities in 2011, enforcing a no-fly-zone. In 2014, Obama authorised airstrikes against ISIL, also known as ISIS, inside Syria and launched a programme to train and arm rebels fighting the group and Syrian government."
    },
    {
        "name": "BARACK OBAMA (2013-2017)",
        "populationstart": 315,
        "populartionend": 324,
        "gdpstart": 15.2,
        "gdpend": 16.5,
        "inflation": 7,
        "deptstart": 15.3,
        "deptend": 17.4,
        "surplusstart": -1000.04,
        "surplusend": -616.00,
        "aidcurrent": 4763067.837,
        "aidconstant": 4761391.671,
        "incarcerationstart": 1570400,
        "incarcerationend": 1561500,
        "deportationstart": 647641,
        "deportationend": 577925,
        "crimesstart": 6573,
        "crimesend": 5479,
        "shootingsvictims": 482,
        "shootingsincidents": 28,
        "dronepakistan": "2004 onwards: 424",
        "droneyemen": "2007 onwards: 32-36",
        "dronesomalia": "2002 onwards: 137-157",
        "droneafghan": "2015 onwards: 626-631",
        "intervation": "Under Obama, the US formally ended its combat mission in Iraq in August 2010.  In 2009, 30,000 more military personnel were deployed to Afghanistan in an attempt to bolster the US presence in the country. In a special operation, US Navy SEALS infiltrated a compound in Pakistan, killing Osama bin Laden. During his second term, Obama ordered air strikes on the Libyan government’s air defence facilities in 2011, enforcing a no-fly-zone. In 2014, Obama authorised airstrikes against ISIL, also known as ISIS, inside Syria and launched a programme to train and arm rebels fighting the group and Syrian government."
    }
]
